---
- name: SFTP-Server | Compute SFTP users with defaults
  ansible.builtin.set_fact:
    _sftp_users: "{{ _sftp_users | default([]) + [item | combine({'home': item.home | default(sftp_home_partition + '/' + item.name)})] }}"
  loop: "{{ sftp_users }}"

- name: SFTP-Server | Create sftp user group
  ansible.builtin.group:
    name: "{{ sftp_group_name }}"
    state: present

- name: SFTP-Server | Alter sftp subsystem entry
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Subsystem(\s+)sftp'
    line: "Subsystem sftp internal-sftp -f AUTH -l VERBOSE"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: SFTP-Server | Restart sshd

- name: SFTP-Server | Add sshd_config block
  ansible.builtin.blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} SFTP-Server {{ sftp_group_name }} block"
    block: |
      Match Group {{ sftp_group_name }}
          ChrootDirectory %h
          AllowTCPForwarding no
          PermitTunnel no
          X11Forwarding no
          ForceCommand internal-sftp -u 002{{ sftp_enable_logging | ternary(' -l VERBOSE', '') }}
          PasswordAuthentication {{ sftp_allow_passwords | ternary('yes', 'no') }}
    validate: /usr/sbin/sshd -t -f %s
  notify: SFTP-Server | Restart sshd

- name: SFTP-Server | Create sftp users
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ sftp_group_name }}"
    groups: "{{ item.groups | default([sftp_group_name]) | join(',') }}"
    append: true
    home: "{{ item.home }}"
    shell: "{{ sftp_nologin_shell }}"
    state: present
  loop: "{{ _sftp_users }}"

- name: SFTP-Server | Correct ownership and permission of home directories
  ansible.builtin.file:
    path: "{{ item.home }}"
    owner: root
    group: root
    mode: '0755'
  loop: "{{ _sftp_users }}"

- name: SFTP-Server | Ensure source web directories exist with SGID
  ansible.builtin.file:
    path: "{{ item.mount_source }}"
    state: directory
    owner: "{{ item.name }}" # or web_group owner
    group: "{{ web_group }}"
    mode: '2775'
  loop: "{{ _sftp_users }}"
  when: item.mount_source is defined

- name: SFTP-Server | (idempotency) Ensure existing bind mount is removed
  ansible.posix.mount:
    path: "{{ item.home }}/ftp-data"
    state: absent
  loop: "{{ _sftp_users }}"
  when: item.mount_source is defined

- name: SFTP-Server | (idempotency) Ensure mount point directory is removed
  ansible.builtin.file:
    path: "{{ item.home }}/ftp-data"
    state: absent
  loop: "{{ _sftp_users }}"
  when: item.mount_source is defined

- name: SFTP-Server | Create mount point directory in user home
  ansible.builtin.file:
    path: "{{ item.home }}/ftp-data"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ _sftp_users }}"
  when: item.mount_source is defined

- name: SFTP-Server | Bind mount web directory
  ansible.posix.mount:
    path: "{{ item.home }}/ftp-data"
    src: "{{ item.mount_source }}"
    opts: bind
    state: mounted
    fstype: none
  loop: "{{ _sftp_users }}"
  when: item.mount_source is defined

- name: SFTP-Server | Install public keys
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  loop: "{{ _sftp_users | subelements('authorized', skip_missing=True) }}"

- name: SFTP-Server | Apply web directory permissions
  ansible.builtin.include_tasks: web_permissions.yml
  when: sftp_manage_web_perms | bool
